version: "3.7"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "8080-8081:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
      - GF_AUTH_BASIC_ENABLED=true # leave true while configuring OAuth
      - GF_AUTH_DISABLE_LOGIN_FORM=false # leave false while configuring OAuth
      - GF_AUTH_OKTA_ENABLED=true
      - GF_AUTH_OKTA_NAME=Okta
      - GF_AUTH_OKTA_ALLOW_SIGN_UP=true
      - GF_AUTH_OKTA_SKIP_ORG_ROLE_SYNC=false
      - GF_AUTH_OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - GF_AUTH_OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
      - GF_AUTH_OKTA_SCOPES=${OKTA_SCOPES}
      - GF_AUTH_OKTA_AUTH_URL=${GODADDY_OKTA_AUTH_URL}
      - GF_AUTH_OKTA_TOKEN_URL=${GODADDY_OKTA_TOKEN_URL}
      - GF_AUTH_OKTA_API_URL=${GODADDY_OKTA_USERINFO_URL}
      - GF_AUTH_OKTA_ALLOWED_GROUPS=${ALLOWED_GODADDY_GROUPS}
      - GF_AUTH_OKTA_ROLE_ATTRIBUTE_PATH=${ROLE_ATTRIBUTE_PATH}
      - GF_SERVER_ROOT_URL=${SERVER_ROOT_URL}
      - GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH=${EMAIL_ATTRIBUTE_PATH}
      - GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP=${ALLOW_INSECURE_EMAIL_LOOKUP}
    volumes:
      - data:/var/lib/grafana
    deploy:
      replicas: 2
      
volumes:
  data:
