version: "3.7"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 8080:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - data:/var/lib/grafana
      
    restart: unless-stopped
      
volumes:
  data:
