version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins_cicd
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Phoenix
    ports:
      - "8082:8080"
      - "55667:50000"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/var/jenkins_home
      
volumes:
  data:
